package main

import(
  "time"
)

type AutoGenerated struct {
	ProtoPayload struct {
		Type              string    `json:""`
		AppID             string    `json:""`
		VersionID         string    `json:""`
		RequestID         string    `json:""`
		IP                string    `json:""`
		StartTime         time.Time `json:""`
		EndTime           time.Time `json:""`
		Latency           string    `json:""`
		MegaCycles        string    `json:""`
		Method            string    `json:""`
		Resource          string    `json:"resource"`
		HTTPVersion       string    `json:""`
		Status            int       `json:""`
		ResponseSize      string    `json:""`
		Referrer          string    `json:""`
		UserAgent         string    `json:""`
		URLMapEntry       string    `json:""`
		Host              string    `json:""`
		Cost              float64   `json:""`
		WasLoadingRequest bool      `json:""`
		InstanceIndex     int       `json:""`
		Finished          bool      `json:""`
		InstanceID        string    `json:""`
		Line              []struct {
			Time       time.Time `json:""`
			Severity   string    `json:""`
			LogMessage string    `json:""`
		} `json:""`
		AppEngineRelease string `json:""`
		TraceID          string `json:""`
		First            bool   `json:""`
		TraceSampled     bool   `json:""`
	} `json:"protoPayload"`
	InsertID    string `json:""`
	HTTPRequest struct {
		Status int `json:""`
	} `json:""`
	Resource struct {
		Type   string `json:""`
		Labels struct {
			ProjectID string `json:""`
			Zone      string `json:""`
			ModuleID  string `json:""`
			VersionID string `json:""`
		} `json:""`
	} `json:""`
	Timestamp time.Time `json:""`
	Severity  string    `json:""`
	Labels    struct {
		CloneID string `json:""`
	} `json:""`
	LogName   string `json:""`
	Operation struct {
		ID       string `json:""`
		Producer string `json:""`
		First    bool   `json:""`
		Last     bool   `json:""`
	} `json:""`
	Trace            string    `json:""`
	ReceiveTimestamp time.Time `json:""`
	TraceSampled     bool      `json:""`
}

